"""modo estricto de busqueda

Revision ID: 5aa847241fa0
Revises: f3c65e437b4c
Create Date: 2026-07-29 11:10:14.546936
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "5aa847241fa0"
down_revision: str | None = "f3c65e437b4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "searches",
        sa.Column("strict_match", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("searches", "strict_match")
    # ### end Alembic commands ###
