"""credenciales del buscador para descubrir perfiles sociales

Instagram y LinkedIn prohíben el rastreo directo en su `robots.txt` pero
permiten que Google y Bing las indexen. El descubrimiento de perfiles se hace
consultando ese índice por la API oficial del buscador, y esas credenciales
son las que se guardan aquí — la clave cifrada, el identificador del motor no
(no es secreto).

Revision ID: 5d0b993aec1c
Revises: 5aa847241fa0
Create Date: 2026-07-29 11:29:41.588405
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5d0b993aec1c'
down_revision: str | None = '5aa847241fa0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('serp_api_key_enc', sa.Text(), nullable=True))
    op.add_column('app_settings', sa.Column('serp_engine_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'serp_engine_id')
    op.drop_column('app_settings', 'serp_api_key_enc')
    # ### end Alembic commands ###
