"""hallazgos web de la empresa para el dossier

Lo que el buscador indexó de cada negocio se guarda en la propia empresa. Cada
consulta al buscador cuesta cuota y la información pública de un negocio
pequeño no cambia de un día para otro: preguntar en cada apertura del panel
sería tirar el presupuesto.

Revision ID: 7aa0a3ea011c
Revises: 5d0b993aec1c
Create Date: 2026-07-29 16:14:41.736877
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7aa0a3ea011c'
down_revision: str | None = '5d0b993aec1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('web_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('companies', sa.Column('web_findings_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'web_findings_at')
    op.drop_column('companies', 'web_findings')
    # ### end Alembic commands ###
